version: '3'
services:
  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "8080:80"

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
